// components/AIAssistant.vue
<template>
  <div
    v-if="isOpen"
    class="w-96 h-full bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl border-l border-slate-200/50 dark:border-slate-700/50 flex flex-col"
  >
    <div class="p-4 border-b border-slate-200/50 dark:border-slate-700/50">
      <div class="flex items-center justify-between">
        <div class="flex items-center space-x-2">
          <div class="w-8 h-8 bg-gradient-to-br from-purple-500 to-blue-500 rounded-lg flex items-center justify-center">
            <Icon name="heroicons:sparkles" class="w-4 h-4 text-white" />
          </div>
          <div>
            <h3 class="font-semibold text-slate-900 dark:text-slate-100">AI Assistant</h3>
            <p class="text-xs text-slate-500 dark:text-slate-400">Powered by GPT-4</p>
          </div>
        </div>
        <UButton variant="ghost" size="sm" @click="$emit('close')">
          <Icon name="heroicons:x-mark" class="w-4 h-4" />
        </UButton>
      </div>
    </div>

    <div class="flex-1 overflow-auto p-4 space-y-4">
      <div
        v-for="(msg, index) in messages"
        :key="index"
        :class="['flex', msg.type === 'user' ? 'justify-end' : 'justify-start']"
      >
        <div
          :class="[
            'max-w-[80%] p-3 rounded-lg',
            msg.type === 'user'
              ? 'bg-blue-500 text-white'
              : 'bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-slate-100'
          ]"
        >
          <p class="text-sm">{{ msg.content }}</p>
          <p class="text-xs opacity-70 mt-1">{{ msg.timestamp }}</p>
        </div>
      </div>

      <div v-if="messages.length === 1" class="space-y-3">
        <p class="text-sm text-slate-600 dark:text-slate-400">Quick queries:</p>
        <UButton
          v-for="(query, index) in quickQueries"
          :key="index"
          variant="outline"
          size="sm"
          @click="handleQuickQuery(query)"
          class="w-full justify-start text-left h-auto p-3 whitespace-normal"
        >
          <div class="flex items-start space-x-2">
            <Icon :name="getQueryIcon(index)" class="w-4 h-4 mt-0.5 flex-shrink-0" />
            <span class="text-sm">{{ query }}</span>
          </div>
        </UButton>
      </div>
    </div>

    <div class="p-4 border-t border-slate-200/50 dark:border-slate-700/50">
      <div class="flex space-x-2">
        <UInput
          v-model="message"
          placeholder="Ask about your retail data..."
          @keypress.enter="handleSendMessage"
          class="flex-1"
        />
        <UButton @click="handleSendMessage" size="sm">
          <Icon name="heroicons:paper-airplane" class="w-4 h-4" />
        </UButton>
      </div>
      <p class="text-xs text-slate-500 dark:text-slate-400 mt-2">
        Try: "Compare facings of Oreo in Ahorramás vs Día"
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  isOpen: Boolean,
})

const emit = defineEmits(['close'])

const message = ref('')
const messages = ref([
  {
    type: 'assistant',
    content: 'Hi! I\'m your AI assistant. Ask me anything about your retail data. For example:',
    timestamp: '10:30 AM',
  },
])

const quickQueries = [
  'Compare Oreo facings in Carrefour vs Día',
  'Show underperforming products in Lidl',
  'Which brands have highest shelf share?',
  'Find images with shelf share < 10%',
]

const handleSendMessage = () => {
  if (!message.value.trim()) return

  const newMessages = [
    ...messages.value,
    {
      type: 'user',
      content: message.value,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    },
    {
      type: 'assistant',
      content: 'I\'m analyzing your request... Based on the current data, here\'s what I found:',
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    },
  ]

  messages.value = newMessages
  message.value = ''
}

const handleQuickQuery = (query) => {
  message.value = query
}

const getQueryIcon = (index) => {
  const icons = [
    'heroicons:chart-bar',
    'heroicons:chat-bubble-left-right',
    'heroicons:chart-bar',
    'heroicons:camera'
  ]
  return icons[index] || 'heroicons:chat-bubble-left-right'
}
</script>

// components/ai-assistant.tsx
"use client"

import type React from "react"

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { X, Send, Sparkles, BarChart3, MessageCircle, Camera } from "lucide-react"

interface Message {
  id: string
  content: string
  sender: "user" | "assistant"
  timestamp: Date
}

interface AIAssistantProps {
  isOpen: boolean
  onClose: () => void
}

export function AIAssistant({ isOpen, onClose }: AIAssistantProps) {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      content: "Hi! I'm your AI assistant. Ask me anything about your retail data. For example:",
      sender: "assistant",
      timestamp: new Date(),
    },
  ])
  const [inputValue, setInputValue] = useState("")
  const scrollAreaRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  const quickQueries = [
    {
      icon: BarChart3,
      text: "Compare Oreo facings in Carrefour vs Día",
      color: "text-blue-500",
    },
    {
      icon: MessageCircle,
      text: "Show underperforming products in Lidl",
      color: "text-green-500",
    },
    {
      icon: BarChart3,
      text: "Which brands have highest shelf share?",
      color: "text-purple-500",
    },
    {
      icon: Camera,
      text: "Find images with shelf share < 10%",
      color: "text-orange-500",
    },
  ]

  useEffect(() => {
    if (isOpen && inputRef.current) {
      inputRef.current.focus()
    }
  }, [isOpen])

  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isOpen) {
        onClose()
      }
    }

    document.addEventListener("keydown", handleEscape)
    return () => document.removeEventListener("keydown", handleEscape)
  }, [isOpen, onClose])

  const handleSendMessage = () => {
    if (!inputValue.trim()) return

    const newMessage: Message = {
      id: Date.now().toString(),
      content: inputValue,
      sender: "user",
      timestamp: new Date(),
    }

    setMessages((prev) => [...prev, newMessage])
    setInputValue("")

    // Simulate AI response
    setTimeout(() => {
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        content:
          "I understand you're asking about retail analytics. Let me analyze the data and provide you with insights based on your query.",
        sender: "assistant",
        timestamp: new Date(),
      }
      setMessages((prev) => [...prev, aiResponse])
    }, 1000)
  }

  const handleQuickQuery = (query: string) => {
    setInputValue(query)
    if (inputRef.current) {
      inputRef.current.focus()
    }
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      handleSendMessage()
    }
  }

  if (!isOpen) return null

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/20 backdrop-blur-sm z-40 transition-opacity duration-300"
        onClick={onClose}
      />

      {/* Panel */}
      <div className="fixed right-0 top-0 h-full w-96 bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-700 shadow-2xl z-50 flex flex-col transition-transform duration-300 ease-out">
        {/* Header */}
        <div className="bg-gradient-to-r from-purple-500 to-blue-500 p-4 text-white">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-white/20 rounded-full p-2">
                <Sparkles className="h-5 w-5" />
              </div>
              <div>
                <h2 className="text-lg font-semibold">AI Assistant</h2>
                <p className="text-sm text-white/80">Powered by GPT-4</p>
              </div>
            </div>
            <Button variant="ghost" size="sm" onClick={onClose} className="text-white hover:bg-white/20 h-8 w-8 p-0">
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Messages */}
        <ScrollArea ref={scrollAreaRef} className="flex-1 p-4">
          <div className="space-y-4">
            {messages.map((message) => (
              <div key={message.id} className={`flex ${message.sender === "user" ? "justify-end" : "justify-start"}`}>
                <div className={`flex items-start space-x-2 max-w-[80%]`}>
                  {message.sender === "assistant" && (
                    <Avatar className="h-8 w-8 bg-gradient-to-r from-purple-500 to-blue-500">
                      <AvatarFallback className="text-white text-xs">AI</AvatarFallback>
                    </Avatar>
                  )}
                  <div
                    className={`rounded-lg p-3 ${
                      message.sender === "user"
                        ? "bg-blue-500 text-white"
                        : "bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-slate-100"
                    }`}
                  >
                    <p className="text-sm">{message.content}</p>
                    <p
                      className={`text-xs mt-1 ${
                        message.sender === "user" ? "text-blue-100" : "text-slate-500 dark:text-slate-400"
                      }`}
                    >
                      {message.timestamp.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                    </p>
                  </div>
                  {message.sender === "user" && (
                    <Avatar className="h-8 w-8 bg-slate-600">
                      <AvatarFallback className="text-white text-xs">JD</AvatarFallback>
                    </Avatar>
                  )}
                </div>
              </div>
            ))}
          </div>
        </ScrollArea>

        {/* Quick Queries */}
        <div className="p-4 border-t border-slate-200 dark:border-slate-700">
          <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-3">Quick queries:</p>
          <div className="space-y-2">
            {quickQueries.map((query, index) => (
              <Button
                key={index}
                variant="ghost"
                size="sm"
                onClick={() => handleQuickQuery(query.text)}
                className="w-full justify-start text-left h-auto p-3 hover:bg-slate-100 dark:hover:bg-slate-800"
              >
                <query.icon className={`h-4 w-4 mr-2 ${query.color}`} />
                <span className="text-sm">{query.text}</span>
              </Button>
            ))}
          </div>
        </div>

        {/* Input */}
        <div className="p-4 bg-slate-50 dark:bg-slate-800/50 border-t border-slate-200 dark:border-slate-700">
          <div className="flex space-x-2">
            <Input
              ref={inputRef}
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Ask about your retail data..."
              className="flex-1 bg-white dark:bg-slate-900 border-slate-300 dark:border-slate-600"
            />
            <Button
              onClick={handleSendMessage}
              disabled={!inputValue.trim()}
              className="bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 text-white"
            >
              <Send className="h-4 w-4" />
            </Button>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">
            Try: "Compare facings of Oreo in Ahorramás vs Día"
          </p>
        </div>
      </div>
    </>
  )
}
