// components/brand-product-table.tsx
"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { ShoppingCart, Euro, Camera, Eye, TrendingUp, TrendingDown } from "lucide-react"

interface BrandProductTableProps {
  selectedChain: string
  selectedBrand: string
  selectedProduct: string
}

export function BrandProductTable({ selectedChain, selectedBrand, selectedProduct }: BrandProductTableProps) {
  const products = [
    {
      brand: "Oreo",
      product: "Original Cookies",
      price: "€2.89",
      facings: 4,
      photos: 12,
      shelfShare: "15.2%",
      trend: "up",
      change: "+2.1%",
    },
    {
      brand: "Kinder",
      product: "Bueno",
      price: "€3.45",
      facings: 2,
      photos: 8,
      shelfShare: "8.7%",
      trend: "down",
      change: "-1.3%",
    },
    {
      brand: "Nestlé",
      product: "KitKat",
      price: "€2.15",
      facings: 3,
      photos: 15,
      shelfShare: "12.4%",
      trend: "up",
      change: "+0.8%",
    },
    {
      brand: "Ferrero",
      product: "Nutella",
      price: "€4.99",
      facings: 5,
      photos: 20,
      shelfShare: "18.9%",
      trend: "up",
      change: "+3.2%",
    },
  ]

  return (
    <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-sm border-slate-200/50 dark:border-slate-700/50">
      <CardHeader>
        <CardTitle className="flex items-center space-x-2">
          <ShoppingCart className="h-5 w-5 text-green-500" />
          <span>Brand & Product Performance</span>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Brand</TableHead>
                <TableHead>Product</TableHead>
                <TableHead className="text-center">Price</TableHead>
                <TableHead className="text-center">Facings</TableHead>
                <TableHead className="text-center">Photos</TableHead>
                <TableHead className="text-center">Shelf Share</TableHead>
                <TableHead className="text-center">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {products.map((product, index) => {
                const TrendIcon = product.trend === "up" ? TrendingUp : TrendingDown

                return (
                  <TableRow
                    key={index}
                    className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors duration-200 group"
                  >
                    <TableCell className="font-medium">
                      <div className="flex items-center space-x-2">
                        <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-500 rounded-lg flex items-center justify-center">
                          <span className="text-white text-xs font-bold">{product.brand.charAt(0)}</span>
                        </div>
                        <span>{product.brand}</span>
                      </div>
                    </TableCell>
                    <TableCell>{product.product}</TableCell>
                    <TableCell className="text-center">
                      <div className="flex items-center justify-center space-x-1">
                        <Euro className="h-3 w-3 text-green-500 group-hover:scale-110 transition-transform duration-200" />
                        <span>{product.price.replace("€", "")}</span>
                      </div>
                    </TableCell>
                    <TableCell className="text-center">
                      <Badge variant="outline" className="group-hover:scale-105 transition-transform duration-200">
                        <Eye className="h-3 w-3 mr-1" />
                        {product.facings}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-center">
                      <Badge variant="outline" className="group-hover:scale-105 transition-transform duration-200">
                        <Camera className="h-3 w-3 mr-1" />
                        {product.photos}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-center">
                      <div className="flex items-center justify-center space-x-2">
                        <span className="font-medium">{product.shelfShare}</span>
                        <Badge
                          variant={product.trend === "up" ? "default" : "destructive"}
                          className={`${
                            product.trend === "up"
                              ? "bg-green-100 text-green-700 dark:bg-green-900/20 dark:text-green-400 hover:scale-105"
                              : "bg-red-100 text-red-700 dark:bg-red-900/20 dark:text-red-400 hover:scale-105"
                          } transition-transform duration-200`}
                        >
                          <TrendIcon
                            className={`h-3 w-3 mr-1 ${product.trend === "up" ? "animate-bounce" : "animate-pulse"}`}
                          />
                          {product.change}
                        </Badge>
                      </div>
                    </TableCell>
                    <TableCell className="text-center">
                      <Button
                        variant="outline"
                        size="sm"
                        className="group-hover:scale-105 transition-transform duration-200 bg-transparent"
                      >
                        View Details
                      </Button>
                    </TableCell>
                  </TableRow>
                )
              })}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  )
}

// components/BrandProductTable.vue
<template>
  <UCard class="bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl border-slate-200/50 dark:border-slate-700/50">
    <template #header>
      <div class="flex items-center space-x-2">
        <Icon name="heroicons:shopping-cart" class="w-5 h-5" />
        <span class="font-semibold">Brand & Product Performance</span>
      </div>
    </template>

    <div class="overflow-x-auto">
      <UTable :rows="products" :columns="columns">
        <template #product-data="{ row }">
          <div class="flex items-center space-x-3">
            <img
              :src="row.image || '/placeholder.svg'"
              :alt="row.product"
              class="w-10 h-10 rounded-lg object-cover"
            />
            <div class="font-medium text-slate-900 dark:text-slate-100">{{ row.product }}</div>
          </div>
        </template>

        <template #brand-data="{ row }">
          <UBadge variant="outline">{{ row.brand }}</UBadge>
        </template>

        <template #shelfShare-data="{ row }">
          <div class="flex items-center space-x-2">
            <span class="font-medium">{{ row.shelfShare }}</span>
            <UBadge
              :color="row.trend === 'up' ? 'green' : 'red'"
              variant="subtle"
            >
              <Icon 
                :name="row.trend === 'up' ? 'heroicons:trending-up' : 'heroicons:trending-down'" 
                class="w-3 h-3 mr-1" 
              />
              {{ row.change }}
            </UBadge>
          </div>
        </template>

        <template #price-data="{ row }">
          <div class="flex items-center">
            <Icon name="heroicons:currency-euro" class="w-4 h-4 mr-1 text-slate-400" />
            {{ row.price }}
          </div>
        </template>

        <template #facings-data="{ row }">
          <div class="flex items-center">
            <Icon name="heroicons:eye" class="w-4 h-4 mr-1 text-slate-400" />
            {{ row.facings }}
          </div>
        </template>

        <template #photos-data="{ row }">
          <div class="flex items-center">
            <Icon name="heroicons:camera" class="w-4 h-4 mr-1 text-slate-400" />
            {{ row.photos }}
          </div>
        </template>

        <template #actions-data="{ row }">
          <UButton variant="ghost" size="sm">
            View Details
          </UButton>
        </template>
      </UTable>
    </div>
  </UCard>
</template>

<script setup>
const props = defineProps({
  selectedChain: String,
  selectedBrand: String,
  selectedProduct: String,
})

const columns = [
  { key: 'product', label: 'Product' },
  { key: 'brand', label: 'Brand' },
  { key: 'supermarket', label: 'Supermarket' },
  { key: 'shelfShare', label: 'Shelf Share' },
  { key: 'price', label: 'Price' },
  { key: 'facings', label: 'Facings' },
  { key: 'photos', label: 'Photos' },
  { key: 'actions', label: 'Actions' },
]

const products = [
  {
    brand: 'Oreo',
    product: 'Original Cookies',
    image: '/placeholder.svg?height=40&width=40',
    supermarket: 'Carrefour',
    shelfShare: '28.5%',
    price: '€2.89',
    facings: 4,
    trend: 'up',
    change: '+2.3%',
    photos: 12,
  },
  {
    brand: 'Kinder',
    product: 'Bueno',
    image: '/placeholder.svg?height=40&width=40',
    supermarket: 'Mercadona',
    shelfShare: '15.2%',
    price: '€3.45',
    facings: 2,
    trend: 'down',
    change: '-1.1%',
    photos: 8,
  },
  {
    brand: 'Nestlé',
    product: 'KitKat',
    image: '/placeholder.svg?height=40&width=40',
    supermarket: 'Día',
    shelfShare: '22.1%',
    price: '€2.15',
    facings: 3,
    trend: 'up',
    change: '+4.2%',
    photos: 15,
  },
  {
    brand: 'Ferrero',
    product: 'Nutella',
    image: '/placeholder.svg?height=40&width=40',
    supermarket: 'Lidl',
    shelfShare: '31.8%',
    price: '€4.99',
    facings: 5,
    trend: 'up',
    change: '+1.8%',
    photos: 20,
  },
  {
    brand: 'Oreo',
    product: 'Golden',
    image: '/placeholder.svg?height=40&width=40',
    supermarket: 'El Corte Inglés',
    shelfShare: '12.4%',
    price: '€3.29',
    facings: 2,
    trend: 'down',
    change: '-0.5%',
    photos: 6,
  },
]
</script>
