// components/SmartInsights.vue
<template>
  <UCard class="bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl border-slate-200/50 dark:border-slate-700/50">
    <template #header>
      <div class="flex items-center space-x-2">
        <Icon name="heroicons:light-bulb" class="w-5 h-5" />
        <span class="font-semibold">Smart Insights</span>
        <UBadge variant="outline">AI-Powered</UBadge>
      </div>
    </template>

    <div class="space-y-4">
      <div
        v-for="(insight, index) in insights"
        :key="index"
        class="p-4 rounded-lg border border-slate-200 dark:border-slate-700 hover:shadow-md transition-shadow"
      >
        <div class="flex items-start space-x-3">
          <div :class="`p-2 rounded-lg bg-${insight.color}-100 dark:bg-${insight.color}-900/20`">
            <Icon :name="insight.icon" :class="`w-4 h-4 text-${insight.color}-600 dark:text-${insight.color}-400`" />
          </div>

          <div class="flex-1 space-y-2">
            <div class="flex items-center justify-between">
              <h3 class="font-medium text-slate-900 dark:text-slate-100">{{ insight.title }}</h3>
              <UBadge :color="getImpactColor(insight.impact)">{{ insight.impact }} Impact</UBadge>
            </div>

            <p class="text-sm text-slate-600 dark:text-slate-400">{{ insight.description }}</p>
          </div>
        </div>
      </div>

      <div class="p-4 bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/10 dark:to-purple-900/10 rounded-lg border border-blue-200 dark:border-blue-800">
        <div class="flex items-center space-x-2 mb-2">
          <Icon name="heroicons:light-bulb" class="w-4 h-4 text-blue-600 dark:text-blue-400" />
          <span class="font-medium text-blue-900 dark:text-blue-100">AI Suggestion</span>
        </div>
        <p class="text-sm text-blue-800 dark:text-blue-200">
          Based on current trends, consider focusing on premium product placement in El Corte Inglés and addressing
          the declining performance in Día supermarkets through targeted promotions.
        </p>
      </div>
    </div>
  </UCard>
</template>

<script setup>
const props = defineProps({
  selectedChain: String,
  selectedBrand: String,
})

const insights = [
  {
    type: 'alert',
    title: 'Underperformance Alert',
    description: 'Oreo brand shows 15% decline in Día supermarkets compared to last month',
    impact: 'High',
    icon: 'heroicons:exclamation-triangle',
    color: 'red',
  },
  {
    type: 'opportunity',
    title: 'Growth Opportunity',
    description: 'Kinder products have highest shelf share growth in El Corte Inglés (+7.3%)',
    impact: 'Medium',
    icon: 'heroicons:trending-up',
    color: 'green',
  },
  {
    type: 'insight',
    title: 'Market Trend',
    description: 'Premium chocolate segment growing 12% faster than standard products',
    impact: 'Medium',
    icon: 'heroicons:light-bulb',
    color: 'blue',
  },
  {
    type: 'recommendation',
    title: 'Action Recommended',
    description: 'Consider increasing facings for Nutella in Carrefour stores (current: 3, optimal: 5)',
    impact: 'High',
    icon: 'heroicons:target',
    color: 'purple',
  },
]

const getImpactColor = (impact) => {
  switch (impact) {
    case 'High':
      return 'red'
    case 'Medium':
      return 'yellow'
    case 'Low':
      return 'green'
    default:
      return 'gray'
  }
}
</script>

// components/smart-insights.tsx
"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Lightbulb, TrendingUp, AlertTriangle, Target, ArrowRight } from "lucide-react"

interface SmartInsightsProps {
  selectedChain: string
  selectedBrand: string
}

export function SmartInsights({ selectedChain, selectedBrand }: SmartInsightsProps) {
  const insights = [
    {
      type: "opportunity",
      title: "Shelf Share Growth Opportunity",
      description:
        "Oreo has 23% higher facings in Carrefour compared to Mercadona. Consider increasing presence in Mercadona.",
      impact: "High",
      icon: TrendingUp,
      color: "green",
    },
    {
      type: "alert",
      title: "Price Positioning Alert",
      description: "Your average price is 15% higher than competitors in the premium cookie segment.",
      impact: "Medium",
      icon: AlertTriangle,
      color: "yellow",
    },
    {
      type: "recommendation",
      title: "Promotional Strategy",
      description: "Stores with promotional displays show 34% higher sales. Consider expanding promotional presence.",
      impact: "High",
      icon: Target,
      color: "blue",
    },
  ]

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case "High":
        return "bg-red-100 text-red-700 dark:bg-red-900/20 dark:text-red-400"
      case "Medium":
        return "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/20 dark:text-yellow-400"
      case "Low":
        return "bg-green-100 text-green-700 dark:bg-green-900/20 dark:text-green-400"
      default:
        return "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-400"
    }
  }

  const getIconColor = (color: string) => {
    switch (color) {
      case "green":
        return "text-green-500"
      case "yellow":
        return "text-yellow-500"
      case "blue":
        return "text-blue-500"
      default:
        return "text-slate-500"
    }
  }

  return (
    <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-sm border-slate-200/50 dark:border-slate-700/50">
      <CardHeader>
        <CardTitle className="flex items-center space-x-2">
          <Lightbulb className="h-5 w-5 text-yellow-500" />
          <span>Smart Insights</span>
          <Badge
            variant="secondary"
            className="ml-auto bg-gradient-to-r from-purple-100 to-blue-100 dark:from-purple-900/20 dark:to-blue-900/20"
          >
            AI Powered
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {insights.map((insight, index) => {
            const Icon = insight.icon

            return (
              <Card
                key={index}
                className="p-4 hover:shadow-md transition-all duration-200 hover:scale-[1.02] bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700"
              >
                <div className="flex items-start space-x-3">
                  <div className={`p-2 rounded-lg bg-${insight.color}-100 dark:bg-${insight.color}-900/20`}>
                    <Icon
                      className={`h-4 w-4 ${getIconColor(insight.color)} ${insight.type === "alert" ? "animate-pulse" : ""}`}
                    />
                  </div>

                  <div className="flex-1 space-y-2">
                    <div className="flex items-center justify-between">
                      <h4 className="font-medium text-slate-900 dark:text-slate-100">{insight.title}</h4>
                      <Badge
                        variant="outline"
                        className={`${getImpactColor(insight.impact)} hover:scale-105 transition-transform duration-200`}
                      >
                        {insight.impact} Impact
                      </Badge>
                    </div>

                    <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{insight.description}</p>

                    <Button
                      variant="ghost"
                      size="sm"
                      className="text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 p-0 h-auto font-medium group"
                    >
                      Learn more
                      <ArrowRight className="h-3 w-3 ml-1 group-hover:translate-x-1 transition-transform duration-200" />
                    </Button>
                  </div>
                </div>
              </Card>
            )
          })}
        </div>
      </CardContent>
    </Card>
  )
}
